### ISSUE TITLE
detail in readme

### ISSUE THREAD

**Issue by WeileiZeng** [TheWanderingCoel/WuhanPneumoniaBotTelegram#1]
I was reading issues in wuhan2020 project and then it takes me here. But I know nothing about telegram. After several minutes of searching information, I realize it is a nice and neat work. How about

add a link explaining what is a telegram bot?

and add some screenshots on how this robot can do now?

**Comment by TheWanderingCoel** [comment]
Sure, I will add a link and some screenshots as quickly as possible.

**Comment by TheWanderingCoel** [comment]
Finished. Thanks for supporting!
