### ISSUE TITLE
您的项目已录入 OpenSourceWuhan 武汉开源

### ISSUE THREAD

**Issue by WeileiZeng** [TheWanderingCoel/WuhanPneumoniaBotTelegram#2]
您好！

感谢您对武汉和开源社区的贡献，您的项目已录入 OpenSourceWuhan 武汉开源,如有疑问请[open an issue](https://github.com/WeileiZeng/OpenSourceWuhan)

武汉开源 [OpenSourceWuhan](https://weileizeng.github.io/OpenSourceWuhan/)
集齐了开源平台上支援武汉的项目，是一个连结各个开源项目的入口。

站点：
[https://weileizeng.github.io/OpenSourceWuhan/](https://weileizeng.github.io/OpenSourceWuhan/)

**Comment by TheWanderingCoel** [comment]
很荣幸能为开源社区和武汉做贡献，这里提一个typo,应该是``TheWandering``而不是``TheWondering``

**Comment by WeileiZeng** [comment]
谢谢提醒！已修正～
